Error and show help if an invalid command is used.

diff --git a/youtube-sync b/youtube-sync
--- a/youtube-sync
+++ b/youtube-sync
@@ -191,4 +191,8 @@ elif [ "$1" = "symlinks" ]; then
 	else
 		update_symlinks "$2"
 	fi
+else
+	>&2 echo "Invalid/Unknown command."
+	showHelp
+	exit 1
 fi
