Prevent garbage files from being created when aborting the update procedure very early (e.g. with CTRL-C), in case update_all_metadata is called for a profile with no entries in the ID directory or update_symlinks is called for a profile with no title entries in the META directory. These cases are now prevented by adding these conditions as early- exit triggers. This fixes #17

diff --git a/youtube-sync b/youtube-sync
--- a/youtube-sync
+++ b/youtube-sync
@@ -61,6 +61,8 @@ function update_all_metadata {
 	num_total=$(find "SYNC/$name/ID/" -maxdepth 1 -name "*.mkv" | wc -l)
 	num_current=1
 
+	if (($num_total == 0)); then return; fi
+
 	for filen in SYNC/$name/ID/*.mkv; do
 		if [ -f "$filen" ]; then
 			if [[ "$filen" =~ /([^/]+)\.mkv$ ]]; then
@@ -117,6 +119,11 @@ function update_symlinks {
 
 	if [ ! -d "SYNC/$1/META" ]; then
 		>&1 echo "Error: /META directory doesn't exist for $1. Have you run the update command?"
+		exit 1
+	fi
+
+	if [ ! "$(find "SYNC/$1/META" -maxdepth 1 -iname "*.title")" ]; then
+		>&1 echo "Error: /META directory seems to be empty for $1. Have you run the update command? Does the profile have videos?"
 		exit 1
 	fi
 
